import NavBar from '@/components/nav/NavBar';
import Footer from '@/components/footer/footer';
import './globals.css';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Cristian Zaragoza',
  description: 'Generated by create next app',
  keywords: 'pintor,Cristian Zaragoza,pintores Rosario',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" type="css/text" href="globals.css" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={inter.className}>
        <NavBar />
        <Suspense fallback={<Loading />}></Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
